// src/app/(admin)/threshold-alert/page.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { ArrowLeft, RotateCcw, Search, Eye, Calendar } from 'lucide-react'
import PageHeader from '@/components/PageHeader'
import DataTable, { Column } from '@/components/DataTable'
import Pagination from '@/components/Pagination'
import Modal from '@/components/Modal'
import Datepicker from '@/components/Datepicker'
import { fetchThresholdAlerts, fetchThresholdAlertTargets, AdminAlert, AdminAlertTarget } from '@/lib/api/endpoints'
import { formatDate, formatNumber, getMonitoringTypeName, MonitoringType, SkuMonitoringUnitType, StoreMonitoringUnitType } from '@/types/enums'

const PER_PAGE = 20

function getSkuTarget(alert: AdminAlert): string {
  const targets = alert.adminAlertTargets ?? []
  switch (alert.skuMonitoringUnitType) {
    case SkuMonitoringUnitType.Sku:
      return `${targets.filter(v => v.skuId).length} 件の商品`
    case SkuMonitoringUnitType.Group:
      return `${targets.filter(v => v.groupId).length} 件の部門`
    case SkuMonitoringUnitType.Department:
      return `${targets.filter(v => v.departmentId).length} 件の中分類`
    case SkuMonitoringUnitType.Line:
      return `${targets.filter(v => v.lineId).length} 件の小分類`
    case SkuMonitoringUnitType.Class:
      return `${targets.filter(v => v.classId).length} 件の細分類`
    default:
      return ''
  }
}

function getStoreTarget(alert: AdminAlert): string {
  switch (alert.storeMonitoringUnitType) {
    case StoreMonitoringUnitType.All:
      return '全店舗'
    case StoreMonitoringUnitType.Store:
      return `${(alert.adminAlertTargets ?? []).filter(v => v.storeId).length} 件の店舗`
    default:
      return ''
  }
}

function ThresholdAlertContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  
  const [alerts, setAlerts] = useState<AdminAlert[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [from, setFrom] = useState(searchParams.get('from') || '')
  const [to, setTo] = useState(searchParams.get('to') || '')
  const [loading, setLoading] = useState(false)

  // Modal state
  const [showModal, setShowModal] = useState(false)
  const [modalTab, setModalTab] = useState(0) // 0=items, 1=stores
  const [targets, setTargets] = useState<AdminAlertTarget[]>([])
  const [targetTotal, setTargetTotal] = useState(0)
  const [targetPage, setTargetPage] = useState(1)
  const [targetAlertId, setTargetAlertId] = useState<string>('')

  const columns: Column<AdminAlert>[] = [
    {
      key: 'objectiveDate',
      label: '対象日',
      sortable: true,
      render: (val: string) => <span className="font-medium text-gray-700">{formatDate(val)}</span>,
    },
    {
      key: 'monitoringType',
      label: 'アラート種類',
      render: (val: number) => (
        <span className="inline-flex items-center rounded bg-red-50 px-2 py-0.5 text-sm font-medium text-red-600 ring-1 ring-inset ring-red-500/10">
          {getMonitoringTypeName(val as MonitoringType)}
        </span>
      ),
    },
    {
      key: 'threshold',
      label: '閾値',
    },
    {
      key: 'skuMonitoringUnitType',
      label: '対象単位',
      render: (_val: number, row: AdminAlert) => (
        <span className="text-gray-800">{getSkuTarget(row)}</span>
      ),
    },
    {
      key: 'storeMonitoringUnitType',
      label: '対象店舗',
      render: (_val: number, row: AdminAlert) => (
        <span className="text-gray-800">{getStoreTarget(row)}</span>
      ),
    },
    {
      key: 'actions',
      label: '操作',
      render: (_val: Record<string, unknown>, row: AdminAlert) => (
        <button
          onClick={e => { e.stopPropagation(); openTargetModal(row) }}
          className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-sm text-gray-700 shadow-sm transition-all hover:bg-gray-50"
        >
          <Eye className="h-3.5 w-3.5" />
          対象を確認
        </button>
      ),
    },
  ]

  const fetchData = useCallback(async (p: number, f?: string, t?: string) => {
    setLoading(true)
    const activeFrom = f !== undefined ? f : from
    const activeTo = t !== undefined ? t : to

    const response = await fetchThresholdAlerts({
      page: p,
      perPage: PER_PAGE,
      from: activeFrom ? new Date(activeFrom) : null,
      to: activeTo ? new Date(activeTo) : null,
    })
    setLoading(false)
    if (response) {
      setAlerts(response.data)
      setTotal(response.total)
    }
  }, [from, to])

  useEffect(() => {
    const pFrom = searchParams.get('from') || ''
    const pTo = searchParams.get('to') || ''
    fetchData(1, pFrom || undefined, pTo || undefined)
  }, [searchParams, fetchData])

  function handleSearch() {
    setPage(1)
    fetchData(1)
  }

  function handleReset() {
    setFrom('')
    setTo('')
    setPage(1)
    fetchData(1)
  }

  function handlePageChange(p: number) {
    setPage(p)
    fetchData(p)
  }

  async function openTargetModal(alert: AdminAlert) {
    setTargetAlertId(alert.id)
    setModalTab(0)
    setTargetPage(1)
    const response = await fetchThresholdAlertTargets({
      id: alert.id,
      page: 1,
      perPage: PER_PAGE,
      isStore: false,
    })
    if (response) {
      setTargets(response.data)
      setTargetTotal(response.total)
      setShowModal(true)
    }
  }

  async function handleTargetTab(tabIndex: number) {
    setModalTab(tabIndex)
    setTargetPage(1)
    const response = await fetchThresholdAlertTargets({
      id: targetAlertId,
      page: 1,
      perPage: PER_PAGE,
      isStore: tabIndex === 1,
    })
    if (response) {
      setTargets(response.data)
      setTargetTotal(response.total)
    }
  }

  async function handleTargetPageChange(p: number) {
    setTargetPage(p)
    const response = await fetchThresholdAlertTargets({
      id: targetAlertId,
      page: p,
      perPage: PER_PAGE,
      isStore: modalTab === 1,
    })
    if (response) {
      setTargets(response.data)
      setTargetTotal(response.total)
    }
  }

  return (
    <div className="space-y-8">
      <PageHeader title="閾値アラートリスト" subtitle="設定した閾値を超過したアラートを検索・確認します" />

      {/* Filter Bar */}
      <div className="rounded-2xl bg-white shadow-[0_2px_8px_rgb(0,0,0,0.04)] ring-1 ring-gray-100 flex flex-col sm:flex-row items-start sm:items-center p-3 gap-4">
        
        {/* Left Side: Icon & Label */}
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-500">
            <Calendar className="h-5 w-5" />
          </div>
          <span className="text-[15px] font-bold text-gray-700 whitespace-nowrap hidden sm:inline-block">対象期間</span>
        </div>

        {/* Date Inputs */}
        <div className="flex items-center gap-2">
          <Datepicker 
            value={from} 
            onChange={setFrom} 
            className="w-48 sm:w-56" 
          />
          <span className="text-gray-300">〜</span>
          <Datepicker 
            value={to} 
            onChange={setTo} 
            className="w-48 sm:w-56" 
          />
        </div>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Action Buttons */}
        <div className="flex w-full sm:w-auto items-center gap-3">
          <button
            onClick={handleReset}
            className="flex flex-1 sm:flex-none items-center justify-center gap-2 rounded-lg bg-white px-4 py-2 text-[15px] font-bold text-gray-500 hover:text-gray-700 transition-colors"
          >
            <RotateCcw className="h-4 w-4" />
            リセット
          </button>
          <button
            onClick={handleSearch}
            disabled={loading}
            className="flex flex-1 sm:flex-none items-center justify-center gap-2 rounded-lg bg-gray-900 px-6 py-2 text-[15px] font-bold text-white hover:bg-gray-800 transition-all active:scale-95 disabled:opacity-60"
          >
            <Search className="h-4 w-4" />
            検索
          </button>
        </div>
      </div>

      {/* Data Table */}
      <div className="overflow-hidden rounded-2xl bg-white shadow-[0_1px_3px_0_rgba(0,0,0,0.1),0_1px_2px_-1px_rgba(0,0,0,0.1)] ring-1 ring-gray-200">
        <DataTable
          columns={columns}
          data={alerts}
          emptyMessage="該当する閾値アラートは見つかりませんでした。"
        />
        {total > 0 && (
          <div className="flex items-center justify-between border-t border-gray-100 bg-gray-50/50 px-6 py-4">
            <span className="text-base text-gray-500">全 {formatNumber(total)} 件のご確認</span>
            <Pagination currentPage={page} totalItems={total} perPage={PER_PAGE} onPageChange={handlePageChange} />
          </div>
        )}
      </div>

      {/* Back Button */}
      <div>
        <button
          onClick={() => router.back()}
          className="inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-base text-gray-600 transition-colors hover:bg-gray-100"
        >
          <ArrowLeft className="h-4 w-4" />
          ダッシュボードへ戻る
        </button>
      </div>

      {/* Target Details Modal */}
      <Modal
        isOpen={showModal}
        onClose={() => setShowModal(false)}
        title="対象詳細の確認"
        size="lg"
        footer={
          <div className="flex w-full items-center justify-between">
            <Pagination
              currentPage={targetPage}
              totalItems={targetTotal}
              perPage={PER_PAGE}
              onPageChange={handleTargetPageChange}
            />
            <button
              onClick={() => setShowModal(false)}
              className="rounded-lg border border-gray-200 bg-white px-5 py-2 text-base text-gray-700 shadow-sm hover:bg-gray-50"
            >
              閉じる
            </button>
          </div>
        }
      >
        {/* Tabs */}
        <div className="mb-5 flex gap-1 rounded-lg bg-gray-100/80 p-1">
          {['対象アイテム', '対象店舗'].map((tab, i) => (
            <button
              key={tab}
              onClick={() => handleTargetTab(i)}
              className={
                modalTab === i
                  ? 'flex-1 rounded-md bg-white py-1.5 text-base text-gray-900 shadow-sm'
                  : 'flex-1 rounded-md py-1.5 text-base text-gray-500 hover:text-gray-700'
              }
            >
              {tab}
            </button>
          ))}
        </div>

        <DataTable
          columns={[{ key: 'targetName', label: '登録名称', render: (val: string) => <span className="font-medium text-gray-700">{val}</span> }]}
          data={targets}
          idKey="id"
        />
      </Modal>
    </div>
  )
}

export default function ThresholdAlertPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-gray-500">読み込み中...</div>}>
      <ThresholdAlertContent />
    </Suspense>
  )
}

// pages/threshold-alert/index.vue
<template>
  <div class="space-y-6">
    <CommonHeader title="閾値アラートリスト" />

    <!-- Filter Bar -->
    <UCard :ui="{ ring: 'ring-1 ring-gray-200', shadow: 'shadow-sm' }">
      <UForm :state="{}" @submit="get(request.page)">
        <div class="flex flex-col gap-4 md:flex-row md:items-center">
          <div class="flex items-center gap-4">
            <label class="whitespace-nowrap text-sm font-bold text-gray-700">
              検索対象期間
            </label>
            <div class="w-40">
              <CommonDatepicker v-model="request.from" />
            </div>
            <span class="text-gray-400">～</span>
            <div class="w-40">
              <CommonDatepicker v-model="request.to" />
            </div>
          </div>
          <div
            class="flex items-center justify-end gap-3 border-t border-gray-100 pt-4 md:ml-auto md:border-t-0 md:pt-0"
          >
            <UButton
              color="gray"
              variant="ghost"
              icon="i-heroicons-arrow-path"
              @click="reset"
              >リセット</UButton
            >
            <UButton
              color="indigo"
              icon="i-heroicons-magnifying-glass"
              @click="get(request.page)"
              >検索する</UButton
            >
          </div>
        </div>
      </UForm>
    </UCard>

    <!-- Data Table -->
    <UCard
      :ui="{
        ring: 'ring-1 ring-gray-200',
        shadow: 'shadow-sm',
        body: { padding: 'p-0 sm:p-0' },
      }"
    >
      <UTable
        :rows="thresholdAlerts"
        :columns="thresholdAlertHeaders"
        class="w-full"
      >
        <template #objectiveDate-data="{ row }">
          <span class="font-medium text-gray-700">{{
            formatterDate(row.objectiveDate)
          }}</span>
        </template>
        <template #monitoringType-data="{ row }">
          <UBadge color="red" variant="subtle" size="sm">
            {{ MonitoringTypes.getName(row.monitoringType) }}
          </UBadge>
        </template>
        <template #skuMonitoringUnitType-data="{ row }">
          <span class="text-gray-800">{{ skuTarget(row) }}</span>
        </template>
        <template #storeMonitoringUnitType-data="{ row }">
          <span class="text-gray-800">{{ storeTarget(row) }}</span>
        </template>
        <template #actions-data="{ row }">
          <UButton
            color="white"
            variant="solid"
            size="xs"
            icon="i-heroicons-eye"
            @click="openTargetModal(row)"
          >
            対象を確認
          </UButton>
        </template>
      </UTable>

      <!-- Pagination Footer -->
      <div
        v-if="thresholdAlertTotal > 0"
        class="flex items-center justify-between rounded-b-lg border-t border-gray-100 bg-gray-50/50 p-4"
      >
        <span class="text-sm text-gray-500">
          全 {{ formatterNumber(thresholdAlertTotal) }} 件のご確認
        </span>
        <UPagination
          v-model="paginationPage"
          :page-count="request.perPage"
          :max="5"
          :total="thresholdAlertTotal"
        />
      </div>
      <div v-else class="p-8 text-center text-gray-500">
        該当する閾値アラートは見つかりませんでした。
      </div>
    </UCard>

    <div class="pt-4">
      <UButton
        color="gray"
        variant="ghost"
        icon="i-heroicons-arrow-left"
        @click="back"
        >ダッシュボードへ戻る</UButton
      >
    </div>

    <!-- Target Details Modal -->
    <UModal v-model="showTargetModal">
      <UCard :ui="{ ring: '', divide: 'divide-y divide-gray-100' }">
        <template #header>
          <div class="flex items-center justify-between">
            <h3 class="text-lg font-bold text-gray-900">対象詳細の確認</h3>
            <UButton
              color="gray"
              variant="ghost"
              icon="i-heroicons-x-mark"
              class="-my-1"
              @click="showTargetModal = false"
            />
          </div>
        </template>

        <UTabs
          :items="[{ label: '対象アイテム' }, { label: '対象店舗' }]"
          class="mb-4"
          @change="onChangedTarget"
        />

        <UTable :rows="targets" :columns="[{ key: 'name', label: '登録名称' }]">
          <template #name-data="{ row }">
            <span class="font-medium text-gray-700">{{ row?.targetName }}</span>
          </template>
        </UTable>

        <template #footer>
          <div class="flex flex-row items-center justify-between">
            <UPagination
              v-model="targetPaginationPage"
              :page-count="targetFetchRequst.perPage"
              :max="5"
              :total="targetTotal"
            />
            <UButton
              color="gray"
              variant="solid"
              label="閉じる"
              @click="showTargetModal = false"
            />
          </div>
        </template>
      </UCard>
    </UModal>
  </div>
</template>

<script setup lang="ts">
import { ThresholdAlertFetchRequestFactory } from '~/composables/api/thresholdAlert/Fetch'
import AppStateTypes from '~/types/enums/AppStateTypes'
import MonitoringTypes from '~/types/enums/MonitoringTypes'
import SkuMonitoringUnitTypes from '~/types/enums/SkuMonitoringUnitTypes'
import StoreMonitoringUnitTypes from '~/types/enums/StoreMonitoringUnitTypes'
import type AdminAlert from '~/types/interfaces/database/AdminAlert'
import type AdminAlertTarget from '~/types/interfaces/database/AdminAlertTarget'
import type AlertFormData from '~/types/interfaces/page/alert/FormData'
import AlertFormDataFactory from '~/types/interfaces/page/alert/FormDataFactory'

const formData =
  servicePersistentStateGet<AlertFormData>(AppStateTypes.AlertFormData, {
    from: (value: string | null) => (value ? new Date(value) : null),
    to: (value: string | null) => (value ? new Date(value) : null),
  }) || new AlertFormDataFactory()
const request = ref({
  ...new ThresholdAlertFetchRequestFactory(),
  from: formData.from,
  to: formData.to,
})
const paginationPage = computed({
  get: () => request.value.page,
  set: (value) => {
    get(value)
  },
})
const thresholdAlerts = ref<AdminAlert[]>([])
const thresholdAlertTotal = ref(0)
const thresholdAlertHeaders = [
  {
    key: 'objectiveDate',
    label: '対象日',
  },
  {
    key: 'monitoringType',
    label: 'アラート種類',
  },
  {
    key: 'threshold',
    label: '閾値',
  },
  {
    key: 'skuMonitoringUnitType',
    label: '対象単位',
  },
  {
    key: 'storeMonitoringUnitType',
    label: '対象店舗',
  },
  {
    key: 'targetDetail',
    label: '操作',
  },
]

async function reset() {
  request.value = new ThresholdAlertFetchRequestFactory()
  await get(1)
}

async function get(page: number) {
  request.value.page = page
  serviceLoadingStart()
  const response = await apiThresholdAlertFetch(request.value)
  serviceLoadingFinish()
  if (!response) {
    return
  }

  thresholdAlerts.value = response.data
  thresholdAlertTotal.value = response.total

  // 検索条件をブラウザに保持する
  servicePersistentStateSet(AppStateTypes.AlertFormData, request.value)
}
await get(1)

function back() {
  useRouter().back()
}

function skuTarget(adminAlert: AdminAlert) {
  switch (adminAlert.skuMonitoringUnitType) {
    case SkuMonitoringUnitTypes.Sku:
      return (
        adminAlert.adminAlertTargets?.filter((v) => v.skuId).length +
        ' 件の商品'
      )
    case SkuMonitoringUnitTypes.Group:
      return (
        adminAlert.adminAlertTargets?.filter((v) => v.groupId).length +
        ' 件の部門'
      )
    case SkuMonitoringUnitTypes.Department:
      return (
        adminAlert.adminAlertTargets?.filter((v) => v.departmentId).length +
        ' 件の中分類'
      )
    case SkuMonitoringUnitTypes.Line:
      return (
        adminAlert.adminAlertTargets?.filter((v) => v.lineId).length +
        ' 件の小分類'
      )
    case SkuMonitoringUnitTypes.Class:
      return (
        adminAlert.adminAlertTargets?.filter((v) => v.classId).length +
        ' 件の細分類'
      )
  }
}

function storeTarget(adminAlert: AdminAlert) {
  switch (adminAlert.storeMonitoringUnitType) {
    case StoreMonitoringUnitTypes.All:
      return '全店舗'
    case StoreMonitoringUnitTypes.Store:
      return (
        adminAlert.adminAlertTargets?.filter((v) => v.storeId).length +
        ' 件の店舗'
      )
  }
}

// 対象を確認するモーダル関連の処理 -------------------------------------------------------------
const showTargetModal = ref(false)
const targetFetchRequst = ref(new ThresholdAlertTargetFetchRequestFactory())
const targetPaginationPage = computed({
  get: () => targetFetchRequst.value.page,
  set: (value) => {
    targetFetch(value)
  },
})
const targets = ref<AdminAlertTarget[]>([])
const targetTotal = ref(0)
async function openTargetModal(adminAlert: AdminAlert) {
  targetFetchRequst.value = new ThresholdAlertTargetFetchRequestFactory(
    adminAlert.id
  )

  const result = await targetFetch(1)

  // 正常に取得できていたらモーダルを展開
  if (result) {
    showTargetModal.value = true
  }
}

async function targetFetch(page: number) {
  targetFetchRequst.value.page = page

  serviceLoadingStart()
  const response = await apiThresholdAlertTargetFetch(targetFetchRequst.value)
  serviceLoadingFinish()

  if (!response) {
    return false
  }

  targets.value = response.data
  targetTotal.value = response.total
  return true
}

function onChangedTarget(index: number) {
  targetFetchRequst.value.isStore = index === 1

  targetFetch(1)
}
// -------------------------------------------------------------------------------------------
</script>

<style scoped></style>
