// pages/order-conditions/[id].vue
<template>
  <div>
    <CommonHeader title="発注条件マスタ 編集" />

    <UForm :state="orderCondition" @submit="onSubmit">
      <div class="flex">
        <UFormGroup label="店舗" class="basis-2/12 pr-5">
          <span class="text-sm">
            {{ orderCondition.storeMaster?.storeName }}
          </span>
        </UFormGroup>
        <UFormGroup label="JAN" class="basis-1/12 pr-5">
          <span class="text-sm">
            {{ orderCondition.storeSkuMaster?.janCode }}
          </span>
        </UFormGroup>
        <UFormGroup label="部門" class="basis-1/12 pr-5">
          <span class="text-sm">
            {{ orderCondition.storeSkuMaster?.groupMaster?.groupName }}
          </span>
        </UFormGroup>
        <UFormGroup label="中分類" class="basis-1/12 pr-5">
          <span class="text-sm">
            {{
              orderCondition.storeSkuMaster?.departmentMaster?.departmentName
            }}
          </span>
        </UFormGroup>
        <UFormGroup label="小分類" class="basis-1/12 pr-5">
          <span class="text-sm">
            {{ orderCondition.storeSkuMaster?.lineMaster?.lineName }}
          </span>
        </UFormGroup>
        <UFormGroup label="細分類" class="basis-1/12 pr-5">
          <span class="text-sm">
            {{ orderCondition.storeSkuMaster?.classMaster?.className }}
          </span>
        </UFormGroup>
        <UFormGroup label="商品名" class="basis-5/12 pr-5">
          <span class="text-sm">
            {{ orderCondition.storeSkuMaster?.skuName }}
          </span>
        </UFormGroup>
      </div>
      <div class="flex pt-5">
        <UFormGroup label="対象期間（開始）" class="basis-2/12 pr-5" required>
          <CommonDatepicker
            v-model="orderCondition.orderConditionStartDate"
            :has-error="apiValidationError.exists('orderConditionStartDate')"
          />
        </UFormGroup>
        <UFormGroup label="対象期間（終了）" class="basis-2/12 pr-5" required>
          <CommonDatepicker
            v-model="orderCondition.orderConditionEndDate"
            :has-error="apiValidationError.exists('orderConditionEndDate')"
          />
        </UFormGroup>
        <UFormGroup label="優先度" class="basis-1/12 pr-5" required>
          <CommonInput
            v-model="orderCondition.orderConditionPriority"
            type="number"
            :has-error="apiValidationError.exists('orderConditionPriority')"
          />
        </UFormGroup>
      </div>
      <CommonErrorMessages
        :messages="
          apiValidationError.get([
            'orderConditionStartDate',
            'orderConditionEndDate',
            'orderConditionPriority',
          ]) as string[]
        "
      />
      <div class="flex pt-5">
        <UFormGroup label="発注方式" class="basis-2/12 pr-5">
          <CommonSelect
            v-model:selected="orderCondition.orderingMethod"
            class="w-full"
            :options="OrderingMethodTypes.getNameValues()"
          />
        </UFormGroup>
        <UFormGroup label="月曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnMonday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnMonday')"
          />
        </UFormGroup>
        <UFormGroup label="火曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnTuesday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnTuesday')"
          />
        </UFormGroup>
        <UFormGroup label="水曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnWednesday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnWednesday')"
          />
        </UFormGroup>
        <UFormGroup label="木曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnThursday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnThursday')"
          />
        </UFormGroup>
        <UFormGroup label="金曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnFriday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnFriday')"
          />
        </UFormGroup>
        <UFormGroup label="土曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnSaturday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnSaturday')"
          />
        </UFormGroup>
        <UFormGroup label="日曜LT" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.leadTimeOnSunday!"
            type="number"
            :has-error="apiValidationError.exists('leadTimeOnSunday')"
          />
        </UFormGroup>
      </div>
      <CommonErrorMessages
        :messages="
          apiValidationError.get([
            'orderingMethod',
            'leadTimeOnMonday',
            'leadTimeOnTuesday',
            'leadTimeOnWednesday',
            'leadTimeOnThursday',
            'leadTimeOnFriday',
            'leadTimeOnSaturday',
            'leadTimeOnSunday',
          ]) as string[]
        "
      />
      <div class="flex pt-5">
        <UFormGroup label="発注ロット" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.orderLot!"
            type="number"
            :has-error="apiValidationError.exists('orderLot')"
          />
        </UFormGroup>
        <UFormGroup label="切上切下区分" class="basis-1/12 pr-5">
          <CommonSelect
            v-model:selected="orderCondition.roundUpDownDefinition"
            class="w-full"
            :options="RoundUpDownTypes.getNameValues()"
          />
        </UFormGroup>

        <UFormGroup label="最低発注数" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.minimumOrderQty!"
            type="number"
            :has-error="apiValidationError.exists('minimumOrderQty')"
          />
        </UFormGroup>
        <UFormGroup
          :label="$config.public.displayStockName"
          class="basis-1/12 pr-5"
        >
          <CommonInput
            v-model="orderCondition.displayStockQty!"
            type="number"
            :has-error="apiValidationError.exists('displayStockQty')"
          />
        </UFormGroup>
        <UFormGroup label="陳列上限数" class="basis-1/12 pr-5">
          <CommonInput
            v-model="orderCondition.displayLimitQty!"
            type="number"
            :has-error="apiValidationError.exists('displayLimitQty')"
          />
        </UFormGroup>
      </div>
      <CommonErrorMessages
        :messages="
          apiValidationError.get([
            'orderLot',
            'roundUpDownDefinition',
            'minimumOrderQty',
            'displayStockQty',
            'displayLimitQty',
          ]) as string[]
        "
      />
      <div class="flex pt-5">
        <UFormGroup label="終売日" class="basis-2/12 pr-5">
          <CommonDatepicker
            v-model="orderCondition.cutDate"
            :has-error="apiValidationError.exists('cutDate')"
          />
        </UFormGroup>
        <UFormGroup label="納品日判定区分" class="basis-4/12 pr-5">
          <CommonSelect
            v-model:selected="orderCondition.deliveryType"
            class="w-full"
            :options="DeliveryDateTypes.getNameValues()"
          />
        </UFormGroup>
      </div>
      <CommonErrorMessages
        :messages="
          apiValidationError.get(['cutDate', 'deliveryType']) as string[]
        "
      />

      <div class="pt-5">
        <UButton color="white" @click="onCancel">戻る</UButton>
        <UButton color="indigo" class="ml-5" @click="onSubmit">保存</UButton>
      </div>
    </UForm>
  </div>
</template>

<script setup lang="ts">
import type { FormSubmitEvent } from '#ui/types'
import type ApiValidationError from '~/types/classes/ApiValidationError'
import DeliveryDateTypes from '~/types/enums/DeliveryDateTypes'
import OrderingMethodTypes from '~/types/enums/OrderingMethodTypes'
import RoundUpDownTypes from '~/types/enums/RoundUpTypes'
import type OrderConditionsMaster from '~/types/interfaces/database/OrderConditionsMaster'

const apiValidationError = ref<ApiValidationError>(
  serviceValidationErrorsInstance()
)

const orderConditionId = Number(useRoute().params.id.toString())
const orderConditionFindResponse = await apiOrderConditionsFind({
  orderConditionId,
})
if (!orderConditionFindResponse) {
  throw createError({
    statusCode: 404,
    statusMessage: 'Not Found',
  })
}
const orderCondition = ref<OrderConditionsMaster>(orderConditionFindResponse)

function onCancel() {
  navigateTo('/order-conditions')
}

async function onSubmit(_event: FormSubmitEvent<OrderConditionsMaster>) {
  serviceLoadingStart()
  const response = await apiOrderConditionsUpdate(orderCondition.value)
  serviceLoadingFinish()
  apiValidationError.value.refresh()

  if (!response) {
    return
  }

  useNuxtApp().$toast.success('入力内容を保存しました。')
}
</script>

<style scoped></style>

// src/app/(admin)/order-conditions/[id]/page.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Save, Loader2 } from 'lucide-react'
import PageHeader from '@/components/PageHeader'
import Datepicker from '@/components/Datepicker'
import { fetchOrderCondition, updateOrderCondition, OrderCondition } from '@/lib/api/endpoints'
import {
  getOrderingMethodTypeName, getOrderingMethodTypeOptions,
  getRoundUpDownTypeName, getRoundUpDownTypeOptions,
  getDeliveryDateTypeName, getDeliveryDateTypeOptions,
} from '@/types/enums'

export default function OrderConditionEditPage() {
  const router = useRouter()
  const params = useParams()
  const id = params.id as string

  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [condition, setCondition] = useState<OrderCondition | null>(null)

  const loadData = useCallback(async () => {
    setLoading(true)
    const response = await fetchOrderCondition(id)
    if (response) {
      setCondition(response)
    }
    setLoading(false)
  }, [id])

  useEffect(() => { loadData() }, [loadData])

  function updateField<K extends keyof OrderCondition>(key: K, value: OrderCondition[K]) {
    setCondition(prev => prev ? { ...prev, [key]: value } : prev)
  }

  async function handleSave() {
    if (!condition) return
    setSaving(true)
    const response = await updateOrderCondition(condition.skuId, condition)
    setSaving(false)
    if (response) {
      router.push('/order-conditions')
    }
  }

  if (loading || !condition) {
    return (
      <div className="flex h-96 items-center justify-center">
        <Loader2 className="h-10 w-10 animate-spin text-gray-300" />
      </div>
    )
  }

  const inputClass = "rounded-xl border border-gray-200 bg-white px-4 py-3 text-base text-gray-800 shadow-sm transition-all focus:border-indigo-400 focus:ring-2 focus:ring-indigo-500/20"
  const selectClass = "rounded-xl border border-gray-200 bg-white px-4 py-3 text-base text-gray-800 shadow-sm transition-all focus:border-indigo-400 focus:ring-2 focus:ring-indigo-500/20"
  const labelClass = "text-sm font-bold text-gray-600 whitespace-nowrap"
  const valueClass = "text-base text-gray-800"

  return (
    <div className="space-y-8 pb-12">
      <PageHeader title="発注条件マスタ 編集" subtitle="商品別の発注条件を編集します" />

      <div className="overflow-hidden rounded-3xl bg-white shadow-xl shadow-gray-200/50 ring-1 ring-gray-100">
        <div className="p-8 space-y-8">
          {/* Read-only Header Info */}
          <div className="grid grid-cols-2 gap-6 sm:grid-cols-3 lg:grid-cols-7">
            <div>
              <p className={labelClass}>店舗</p>
              <p className={valueClass}>{condition.storeMaster?.storeName || condition.storeName}</p>
            </div>
            <div>
              <p className={labelClass}>JAN</p>
              <p className={valueClass}>{condition.storeSkuMaster?.janCode || condition.skuId}</p>
            </div>
            <div>
              <p className={labelClass}>部門</p>
              <p className={valueClass}>{condition.storeSkuMaster?.groupMaster?.groupName || '—'}</p>
            </div>
            <div>
              <p className={labelClass}>中分類</p>
              <p className={valueClass}>{condition.storeSkuMaster?.departmentMaster?.departmentName || '—'}</p>
            </div>
            <div>
              <p className={labelClass}>小分類</p>
              <p className={valueClass}>{condition.storeSkuMaster?.lineMaster?.lineName || '—'}</p>
            </div>
            <div>
              <p className={labelClass}>細分類</p>
              <p className={valueClass}>{condition.storeSkuMaster?.classMaster?.className || '—'}</p>
            </div>
            <div className="col-span-2 sm:col-span-1">
              <p className={labelClass}>商品名</p>
              <p className={valueClass}>{condition.storeSkuMaster?.skuName || condition.skuName}</p>
            </div>
          </div>

          <hr className="border-gray-100" />

          {/* Editable: Period + Priority */}
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <div className="space-y-2">
              <label className={labelClass}>対象期間（開始）<span className="text-red-500 ml-1">*</span></label>
              <Datepicker
                value={condition.orderConditionStartDate || ''}
                onChange={(val) => updateField('orderConditionStartDate', val)}
              />
            </div>
            <div className="space-y-2">
              <label className={labelClass}>対象期間（終了）<span className="text-red-500 ml-1">*</span></label>
              <Datepicker
                value={condition.orderConditionEndDate || ''}
                onChange={(val) => updateField('orderConditionEndDate', val)}
              />
            </div>
            <div className="space-y-2">
              <label className={labelClass}>優先度 <span className="text-red-500 ml-1">*</span></label>
              <input
                type="number"
                value={condition.orderConditionPriority ?? ''}
                onChange={e => updateField('orderConditionPriority', Number(e.target.value))}
                className={`${inputClass} w-full`}
              />
            </div>
          </div>

          {/* Ordering Method + Lead Times */}
          <div>
            <h3 className="mb-4 text-base font-bold text-gray-800">発注方式 ＆ リードタイム</h3>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
              <div className="space-y-2 sm:col-span-2 lg:col-span-2 xl:col-span-2">
                <label className={labelClass}>発注方式</label>
                <select
                  value={condition.orderingMethod}
                  onChange={e => updateField('orderingMethod', Number(e.target.value))}
                  className={`${selectClass} w-full`}
                >
                  {getOrderingMethodTypeOptions().map(opt => (
                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                  ))}
                </select>
              </div>
              {[
                { key: 'leadTimeOnMonday' as const, label: '月曜LT' },
                { key: 'leadTimeOnTuesday' as const, label: '火曜LT' },
                { key: 'leadTimeOnWednesday' as const, label: '水曜LT' },
                { key: 'leadTimeOnThursday' as const, label: '木曜LT' },
                { key: 'leadTimeOnFriday' as const, label: '金曜LT' },
                { key: 'leadTimeOnSaturday' as const, label: '土曜LT' },
              ].map(({ key, label }) => (
                <div key={key} className="space-y-2">
                  <label className={labelClass}>{label}</label>
                  <input
                    type="number"
                    value={condition[key] ?? ''}
                    onChange={e => updateField(key, e.target.value ? Number(e.target.value) : null)}
                    className={`${inputClass} w-full`}
                  />
                </div>
              ))}
            </div>
            <div className="mt-4 grid gap-4 sm:grid-cols-4 lg:grid-cols-8">
              <div className="space-y-2">
                <label className={labelClass}>日曜LT</label>
                <input
                  type="number"
                  value={condition.leadTimeOnSunday ?? ''}
                  onChange={e => updateField('leadTimeOnSunday', e.target.value ? Number(e.target.value) : null)}
                  className={`${inputClass} w-full`}
                />
              </div>
            </div>
          </div>

          {/* Order Lot, Rounding, Min Order, Display Stock, Display Limit */}
          <div>
            <h3 className="mb-4 text-base font-bold text-gray-800">発注条件</h3>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
              <div className="space-y-2">
                <label className={labelClass}>発注ロット</label>
                <input
                  type="number"
                  value={condition.orderLot ?? ''}
                  onChange={e => updateField('orderLot', e.target.value ? Number(e.target.value) : null)}
                  className={`${inputClass} w-full`}
                />
              </div>
              <div className="space-y-2">
                <label className={labelClass}>切上切下区分</label>
                <select
                  value={condition.roundUpDownDefinition}
                  onChange={e => updateField('roundUpDownDefinition', Number(e.target.value))}
                  className={`${selectClass} w-full`}
                >
                  {getRoundUpDownTypeOptions().map(opt => (
                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                  ))}
                </select>
              </div>
              <div className="space-y-2">
                <label className={labelClass}>最低発注数</label>
                <input
                  type="number"
                  value={condition.minimumOrderQty ?? ''}
                  onChange={e => updateField('minimumOrderQty', e.target.value ? Number(e.target.value) : null)}
                  className={`${inputClass} w-full`}
                />
              </div>
              <div className="space-y-2">
                <label className={labelClass}>見栄え在庫数</label>
                <input
                  type="number"
                  value={condition.displayStockQty ?? ''}
                  onChange={e => updateField('displayStockQty', e.target.value ? Number(e.target.value) : null)}
                  className={`${inputClass} w-full`}
                />
              </div>
              <div className="space-y-2">
                <label className={labelClass}>陳列上限数</label>
                <input
                  type="number"
                  value={condition.displayLimitQty ?? ''}
                  onChange={e => updateField('displayLimitQty', e.target.value ? Number(e.target.value) : null)}
                  className={`${inputClass} w-full`}
                />
              </div>
            </div>
          </div>

          {/* Cut Date + Delivery Type */}
          <div>
            <h3 className="mb-4 text-base font-bold text-gray-800">終売・納品</h3>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <div className="space-y-2">
                <label className={labelClass}>終売日</label>
                <Datepicker
                  value={condition.cutDate || ''}
                  onChange={(val) => updateField('cutDate', val || null)}
                />
              </div>
              <div className="space-y-2 sm:col-span-2">
                <label className={labelClass}>納品日判定区分</label>
                <select
                  value={condition.deliveryType}
                  onChange={e => updateField('deliveryType', Number(e.target.value))}
                  className={`${selectClass} w-full max-w-lg`}
                >
                  {getDeliveryDateTypeOptions().map(opt => (
                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                  ))}
                </select>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-3 border-t border-gray-100 bg-gray-50/50 px-8 py-5">
          <button
            onClick={() => router.push('/order-conditions')}
            className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-6 py-3 text-base text-gray-700 shadow-sm transition-all hover:bg-gray-50"
          >
            <ArrowLeft className="h-4 w-4" />
            戻る
          </button>
          <button
            onClick={handleSave}
            disabled={saving}
            className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-8 py-3 text-base font-semibold text-white shadow-sm transition-all hover:bg-indigo-700 active:scale-95 disabled:opacity-50"
          >
            {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            保存
          </button>
        </div>
      </div>
    </div>
  )
}
